import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 4,
  tables: [
    tableSchema({
      name: 'users',
      columns: [
        { name: 'display_name', type: 'string' },
        { name: 'role', type: 'string' },
        { name: 'public_key', type: 'string' },
        { name: 'public_key_hash', type: 'string' },
        { name: 'last_seen_at', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'messages',
      columns: [
        { name: 'sender_id', type: 'string' },
        { name: 'receiver_id', type: 'string', isOptional: true },
        { name: 'conversation_id', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'payload', type: 'string' },
        { name: 'nonce', type: 'string', isOptional: true },
        { name: 'ttl', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sos_reports',
      columns: [
        { name: 'sender_id', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'severity', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'media_chunks',
      columns: [
        { name: 'record_id', type: 'string' },
        { name: 'record_type', type: 'string' },
        { name: 'chunk_index', type: 'number' },
        { name: 'chunk_total', type: 'number' },
        { name: 'data', type: 'string' },
        { name: 'nonce', type: 'string', isOptional: true },
        { name: 'file_name', type: 'string', isOptional: true },
        { name: 'mime_type', type: 'string', isOptional: true },
        { name: 'file_size', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'media_transfers',
      columns: [
        { name: 'record_id', type: 'string' },
        { name: 'message_id', type: 'string' },
        { name: 'file_name', type: 'string' },
        { name: 'mime_type', type: 'string' },
        { name: 'file_size', type: 'number' },
        { name: 'total_chunks', type: 'number' },
        { name: 'received_chunks', type: 'number' },
        { name: 'local_uri', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'conversations',
      columns: [
        { name: 'conversation_id', type: 'string' },
        { name: 'last_message_preview', type: 'string', isOptional: true },
        { name: 'last_message_at', type: 'number', isOptional: true },
        { name: 'last_message_type', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'conversation_participants',
      columns: [
        { name: 'conversation_id', type: 'string', isIndexed: true },
        { name: 'peer_id', type: 'string' },
        { name: 'peer_name', type: 'string' },
        { name: 'last_read_at', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_outbox',
      columns: [
        { name: 'record_id', type: 'string' },
        { name: 'record_type', type: 'string' },
        { name: 'operation', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'retry_count', type: 'number' },
        { name: 'last_error', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'peer_keys',
      columns: [
        { name: 'peer_id', type: 'string', isIndexed: true },
        { name: 'their_public_key', type: 'string' },
        { name: 'fingerprint_hex', type: 'string' },
        { name: 'first_seen_at', type: 'number' },
        { name: 'last_seen_at', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'pending_messages',
      columns: [
        { name: 'message_id', type: 'string' },
        { name: 'envelope_json', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'target_peer_id', type: 'string', isOptional: true },
        { name: 'ttl_at_queue', type: 'number' },
        { name: 'expires_at', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
